sberdevices/assistant-client

- README.md
> Исправлено описание readme

- package-lock.json
- package.json
- src/index.ts
> Проверять срок действия токена и показывать ошибки по истечении

- cypress/plugins/index.js
- src/dev.ts
> messageId должен быть одинаковый в systemMessage и text при отправке текста

- src/dev.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>1.1.3-canary.51.eb7663ab912681c9921b58b8434133cbe9f8cfb6.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@1.1.3-canary.51.eb7663ab912681c9921b58b8434133cbe9f8cfb6.0
yarn add @sberdevices/assistant-client@1.1.3-canary.51.eb7663ab912681c9921b58b8434133cbe9f8cfb6.0
```
</details>
> fix: AssistantCharacterCommand приходит только 1 раз

- .gitignore
- cypress/integration/clientMethods.spec.ts
- cypress/support/helpers/clientMethods.helpers.ts
- cypress/support/helpers/socket.helpers.ts
- src/NativePanel/NativePanel.tsx
- src/client.ts
- src/createNavigatorAudioProvider.ts
- src/createVoiceListener.ts
- src/createVoicePlayer.ts
- src/dev.ts
- src/index.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>2.0.0-canary.47.c89de6ac5a5aaf33bb22f5878af6e2b5d798ad78.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.0.0-canary.47.c89de6ac5a5aaf33bb22f5878af6e2b5d798ad78.0
yarn add @sberdevices/assistant-client@2.0.0-canary.47.c89de6ac5a5aaf33bb22f5878af6e2b5d798ad78.0
```
</details>
> Рефакторинг работы с голосом

- src/index.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>2.2.0-canary.58.f73e9ac794e22bf14a958314a79b9a47704e1438.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.2.0-canary.58.f73e9ac794e22bf14a958314a79b9a47704e1438.0
yarn add @sberdevices/assistant-client@2.2.0-canary.58.f73e9ac794e22bf14a958314a79b9a47704e1438.0
```
</details>
> feat: ts-дженерики для входящих команд ассистента

- examples/todo-canvas-app/package-lock.json
- src/dev.ts
- src/index.ts
- src/mock.ts
- src/record/index.tsx
- src/record/offline-player.ts
- src/record/online-player.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>2.3.0-canary.54.57b4fa4d7264c6071f574dc1dbb73735dfb2fb1a.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.3.0-canary.54.57b4fa4d7264c6071f574dc1dbb73735dfb2fb1a.0
yarn add @sberdevices/assistant-client@2.3.0-canary.54.57b4fa4d7264c6071f574dc1dbb73735dfb2fb1a.0
```
</details>
> feat: Утилиты для тестирования смартапов

- README.md
- src/createRecoveryStateRepository.ts
- src/dev.ts
- src/typings.ts
* Поддержать insets
* Поддержать smart_app_error
* Поддержать recoveryState
<details>
<summary>📦 Published PR as canary version: <code>2.4.0-canary.66.9cbe72cae1f80086cd3a63695f4056250fffe5f2.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.4.0-canary.66.9cbe72cae1f80086cd3a63695f4056250fffe5f2.0
yarn add @sberdevices/assistant-client@2.4.0-canary.66.9cbe72cae1f80086cd3a63695f4056250fffe5f2.0
```
</details>
> feat: Синхронизация с нативным сдк

- examples/umd-example/README.md
- examples/umd-example/index.html
> docs: Пример интеграции через script

- src/mock.ts
<details>
<summary>📦 Published PR as canary version: <code>2.4.1-canary.68.9c1e7e987e4fed8d01f7b732e1e738ebe8cd252d.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.4.1-canary.68.9c1e7e987e4fed8d01f7b732e1e738ebe8cd252d.0
yarn add @sberdevices/assistant-client@2.4.1-canary.68.9c1e7e987e4fed8d01f7b732e1e738ebe8cd252d.0
```
</details>
> fix: Добавлены дженерики в мок

- src/dev.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>2.6.0-canary.73.32a4e319535a88e140d62f8431916719eee4f971.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.6.0-canary.73.32a4e319535a88e140d62f8431916719eee4f971.0
yarn add @sberdevices/assistant-client@2.6.0-canary.73.32a4e319535a88e140d62f8431916719eee4f971.0
```
</details>
> feat: Поддержка флага auto_listening

- cypress/integration/createAssistant.spec.ts
- cypress/integration/createAssistantDev.spec.ts
- src/dev.ts
- src/index.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>2.7.0-canary.74.c934e4283921c6cd31fa3d2a153b5d9f8f49bb0c.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.7.0-canary.74.c934e4283921c6cd31fa3d2a153b5d9f8f49bb0c.0
yarn add @sberdevices/assistant-client@2.7.0-canary.74.c934e4283921c6cd31fa3d2a153b5d9f8f49bb0c.0
```
</details>
> feat: Убрать дубли appInitialData в onData

- src/createMusicRecognizer.ts
- src/mtt/index.d.ts
- src/mtt/index.js
- src/mtt/index.proto
<details>
<summary>📦 Published PR as canary version: <code>2.9.1-canary.78.554376f5cd657df6ad718e8f75efc7b5ae8dbb72.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.9.1-canary.78.554376f5cd657df6ad718e8f75efc7b5ae8dbb72.0
yarn add @sberdevices/assistant-client@2.9.1-canary.78.554376f5cd657df6ad718e8f75efc7b5ae8dbb72.0
```
</details>
> fix: декодинг мтт

- package-lock.json
- package.json
> chore: update axios@0.21.1

- cypress/integration/createAssistant.spec.ts
- cypress/integration/createAssistantDev.spec.ts
- src/dev.ts
- src/index.ts
<details>
<summary>📦 Published PR as canary version: <code>2.9.2-canary.83.4d2d73245d2244318efa37864b47325b19935288.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.9.2-canary.83.4d2d73245d2244318efa37864b47325b19935288.0
yarn add @sberdevices/assistant-client@2.9.2-canary.83.4d2d73245d2244318efa37864b47325b19935288.0
```
</details>
> fix: не падать, если appInitialData нет

- README.md
- cypress/integration/createAssistant.spec.ts
- package-lock.json
- package.json
- src/index.ts
- src/nanoobservable.ts
closes #6 
<details>
<summary>📦 Published PR as canary version: <code>2.10.0-canary.79.52bfe5a7f354c4a3c5b5953837274d003ede93db.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.10.0-canary.79.52bfe5a7f354c4a3c5b5953837274d003ede93db.0
yarn add @sberdevices/assistant-client@2.10.0-canary.79.52bfe5a7f354c4a3c5b5953837274d003ede93db.0
```
</details>
> Возвращать observable при отправке команд

- package-lock.json
- package.json
- src/dev.ts
- src/proto/index.js
<details>
<summary>📦 Published PR as canary version: <code>2.10.1-canary.91.cfc10bbe330aea82a07ea223c212af14fc582c5b.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.10.1-canary.91.cfc10bbe330aea82a07ea223c212af14fc582c5b.0
yarn add @sberdevices/assistant-client@2.10.1-canary.91.cfc10bbe330aea82a07ea223c212af14fc582c5b.0
```
</details>
> Ie11 fixes

- src/createMusicRecognizer.ts
- src/createSpeechRecognizer.ts
- src/createVoiceListener.ts
<details>
<summary>📦 Published PR as canary version: <code>2.10.2-canary.94.e2aba4c1fd45236de4a74d9290728f78790087b5.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.10.2-canary.94.e2aba4c1fd45236de4a74d9290728f78790087b5.0
yarn add @sberdevices/assistant-client@2.10.2-canary.94.e2aba4c1fd45236de4a74d9290728f78790087b5.0
```
</details>
> Не показывать анимацию при запрете доступа к микрофону

- src/createMusicRecognizer.ts
- src/createSpeechRecognizer.ts
<details>
<summary>📦 Published PR as canary version: <code>2.10.3-canary.95.a827465636976d0d4bc61a8bd356048f4186b1cb.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.10.3-canary.95.a827465636976d0d4bc61a8bd356048f4186b1cb.0
yarn add @sberdevices/assistant-client@2.10.3-canary.95.a827465636976d0d4bc61a8bd356048f4186b1cb.0
```
</details>
> fix: При нажатии на лавашар во время запроса не отображается бабл запроса

- .huskyrc.json
- .lintstagedrc
- .prettierignore
- README.md
- cypress/integration/createAssistant.spec.ts
- cypress/integration/sendAction.spec.ts
- package-lock.json
- package.json
- src/index.ts
- src/typings.ts
Closes #88 
<details>
<summary>📦 Published PR as canary version: <code>2.11.0-canary.89.74a3bf7281113c9de2365bc5307ecc768e0f5167.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.11.0-canary.89.74a3bf7281113c9de2365bc5307ecc768e0f5167.0
yarn add @sberdevices/assistant-client@2.11.0-canary.89.74a3bf7281113c9de2365bc5307ecc768e0f5167.0
```
</details>
> Подписка на command и error, метод sendAction

- src/createMusicRecognizer.ts
- src/createSpeechRecognizer.ts
<details>
<summary>📦 Published PR as canary version: <code>2.11.1-canary.96.c2d5e659995d90bbec3ad6edd1a43757f0b52931.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.11.1-canary.96.c2d5e659995d90bbec3ad6edd1a43757f0b52931.0
yarn add @sberdevices/assistant-client@2.11.1-canary.96.c2d5e659995d90bbec3ad6edd1a43757f0b52931.0
```
</details>
> Не бросать ошибку при запрете доступа к микрофону

- src/createVoicePlayer.ts
<details>
<summary>📦 Published PR as canary version: <code>2.11.2-canary.97.987759fc44c8f795e4220393b16666ce743e6af6.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.11.2-canary.97.987759fc44c8f795e4220393b16666ce743e6af6.0
yarn add @sberdevices/assistant-client@2.11.2-canary.97.987759fc44c8f795e4220393b16666ce743e6af6.0
```
</details>
> fix: Добавить метод остановки воспроизведения текущей очереди озвучки

- src/createVoicePlayer.ts
<details>
<summary>📦 Published PR as canary version: <code>2.11.3-canary.98.d553dbb9a97243f506448692fd9a252f7ec76729.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.11.3-canary.98.d553dbb9a97243f506448692fd9a252f7ec76729.0
yarn add @sberdevices/assistant-client@2.11.3-canary.98.d553dbb9a97243f506448692fd9a252f7ec76729.0
```
</details>
> Проигрывание озвучки после остановки

- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>2.11.4-canary.100.aa24d4618e2180205df142e5c61b3bcd7d97f92e.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.11.4-canary.100.aa24d4618e2180205df142e5c61b3bcd7d97f92e.0
yarn add @sberdevices/assistant-client@2.11.4-canary.100.aa24d4618e2180205df142e5c61b3bcd7d97f92e.0
```
</details>
> fix: расширил интерфейс AssistantAppContext

- README.md
- cypress/integration/createAssistant.spec.ts
- cypress/integration/createAssistantDev.spec.ts
- src/dev.ts
- src/index.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>2.11.6-canary.105.716a05dce76c52c9d55c6b817433a3fc6cca5fcf.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.11.6-canary.105.716a05dce76c52c9d55c6b817433a3fc6cca5fcf.0
yarn add @sberdevices/assistant-client@2.11.6-canary.105.716a05dce76c52c9d55c6b817433a3fc6cca5fcf.0
```
</details>
> fix: Команда 'back' не приходит

- README.md
- cypress/integration/createAssistant.spec.ts
- src/createRecoveryStateRepository.ts
- src/dev.ts
- src/index.ts
- src/mock.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>2.11.7-canary.108.ca7e45a83cbfec1c1e7cafd3897761592d270f88.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.11.7-canary.108.ca7e45a83cbfec1c1e7cafd3897761592d270f88.0
yarn add @sberdevices/assistant-client@2.11.7-canary.108.ca7e45a83cbfec1c1e7cafd3897761592d270f88.0
```
</details>
> Эмитить initialData в on('data'), если не был вызван getInitialData

- src/proto/index.d.ts
- src/proto/index.js
- src/proto/index.proto
<details>
<summary>📦 Published PR as canary version: <code>2.11.8--canary.110.79495163f888e0e21ef7e72e49333a2bd1f18ace.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.11.8--canary.110.79495163f888e0e21ef7e72e49333a2bd1f18ace.0
yarn add @sberdevices/assistant-client@2.11.8--canary.110.79495163f888e0e21ef7e72e49333a2bd1f18ace.0
```
</details>
> fix: Добавление поля tenant в Device

- src/NativePanel/NativePanel.tsx
- Верстка по макетам
- Убрал "Попробуйте" (потому что на макетах и в проде этого нет)
- Добавил иконку клавиатуры для mobile
<details>
<summary>📦 Published PR as canary version: <code>2.11.9--canary.111.bf547e8401c7516035e045f3318d79e29cffb029.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.11.9--canary.111.bf547e8401c7516035e045f3318d79e29cffb029.0
yarn add @sberdevices/assistant-client@2.11.9--canary.111.bf547e8401c7516035e045f3318d79e29cffb029.0
```
</details>
> new native panel - Верстка по макетам

- cypress/integration/clientWebsockets.spec.ts
- cypress/support/helpers/clientMethods.helpers.ts
- cypress/support/helpers/socket.helpers.ts
- src/client.ts
- src/clientMethods.ts
- src/dev.ts
- src/index.ts
- src/voice-player/index.ts
- src/voice-player/silence-generator.ts
- src/voice-player/track-stream.ts
<details>
<summary>📦 Published PR as canary version: <code>2.12.0--canary.114.040ea6ff05e0697ac3f5a66cbf9b8c7c440f3e3d.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.12.0--canary.114.040ea6ff05e0697ac3f5a66cbf9b8c7c440f3e3d.0
yarn add @sberdevices/assistant-client@2.12.0--canary.114.040ea6ff05e0697ac3f5a66cbf9b8c7c440f3e3d.0
```
</details>
> fix: Воспроизведение озвучки в safari

- src/dev.ts
<details>
<summary>📦 Published PR as canary version: <code>2.13.0--canary.116.0c5a14a619419f87151c9c8984b84bfb34d72182.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.13.0--canary.116.0c5a14a619419f87151c9c8984b84bfb34d72182.0
yarn add @sberdevices/assistant-client@2.13.0--canary.116.0c5a14a619419f87151c9c8984b84bfb34d72182.0
```
</details>
> feat: добавил features и capabilities как  параметры initializeAssistantSDK

- src/voice-player/index.ts
<details>
<summary>📦 Published PR as canary version: <code>2.14.1--canary.120.185465c785f17011ad97727603b981b861492854.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.14.1--canary.120.185465c785f17011ad97727603b981b861492854.0
yarn add @sberdevices/assistant-client@2.14.1--canary.120.185465c785f17011ad97727603b981b861492854.0
```
</details>
> fix: В консоль не падают ошибки в ie

- src/voice-player/index.ts
<details>
<summary>📦 Published PR as canary version: <code>2.14.2--canary.121.fa69777f38ac8fcda22426f80e1ee691cbc22732.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.14.2--canary.121.fa69777f38ac8fcda22426f80e1ee691cbc22732.0
yarn add @sberdevices/assistant-client@2.14.2--canary.121.fa69777f38ac8fcda22426f80e1ee691cbc22732.0
```
</details>
> ssr снова работает

- src/clientMethods.ts
- src/index.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>2.15.0--canary.119.1c4c2e35f4861700dc383473bdc5eb928a8da427.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.15.0--canary.119.1c4c2e35f4861700dc383473bdc5eb928a8da427.0
yarn add @sberdevices/assistant-client@2.15.0--canary.119.1c4c2e35f4861700dc383473bdc5eb928a8da427.0
```
</details>
> feat: assistant host postmessage for iframe

- src/proto/index.d.ts
- src/proto/index.js
- src/proto/index.proto
<details>
<summary>📦 Published PR as canary version: <code>2.15.1--canary.123.1cea42c1ef72e9d85cb7c81eadcc51809f8d7dd6.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.15.1--canary.123.1cea42c1ef72e9d85cb7c81eadcc51809f8d7dd6.0
yarn add @sberdevices/assistant-client@2.15.1--canary.123.1cea42c1ef72e9d85cb7c81eadcc51809f8d7dd6.0
```
</details>
> fix: added field Message.content.cancel

- cypress/support/helpers/clientMethods.helpers.ts
- cypress/support/helpers/socket.helpers.ts
- src/client.ts
- src/clientMethods.ts
<details>
<summary>📦 Published PR as canary version: <code>2.15.4--canary.126.37f78c828f378be77f9af3adae78c9d0c888d67f.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.15.4--canary.126.37f78c828f378be77f9af3adae78c9d0c888d67f.0
yarn add @sberdevices/assistant-client@2.15.4--canary.126.37f78c828f378be77f9af3adae78c9d0c888d67f.0
```
</details>
> Корректная отправка сообщений из очереди после вызова updateDefaults

- cypress/integration/createAssistantDev.spec.ts
- src/client.ts
<details>
<summary>📦 Published PR as canary version: <code>2.16.1--canary.128.f1a19a9f078f48d7aaabab806c6193cc22afe52e.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@2.16.1--canary.128.f1a19a9f078f48d7aaabab806c6193cc22afe52e.0
yarn add @sberdevices/assistant-client@2.16.1--canary.128.f1a19a9f078f48d7aaabab806c6193cc22afe52e.0
```
</details>
> fix: обработка ошибок коннекта

- src/assistant/assistant.ts
<details>
<summary>📦 Published PR as canary version: <code>3.0.1--canary.133.9872db671e7586f46d55ec048488eeda780c9b17.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.0.1--canary.133.9872db671e7586f46d55ec048488eeda780c9b17.0
yarn add @sberdevices/assistant-client@3.0.1--canary.133.9872db671e7586f46d55ec048488eeda780c9b17.0
```
</details>
> Отправлять appInfo в ответ на запрос пермишенов

- src/assistant/assistant.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>3.1.0--canary.134.924b11e784307d463503e4e2b41f79eceb6b4396.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.1.0--canary.134.924b11e784307d463503e4e2b41f79eceb6b4396.0
yarn add @sberdevices/assistant-client@3.1.0--canary.134.924b11e784307d463503e4e2b41f79eceb6b4396.0
```
</details>
> feat: эмитить ActionCommand приходящие в systemMessage

- src/index.ts
<details>
<summary>📦 Published PR as canary version: <code>3.1.1--canary.135.ea4d71e2036f9323fb24bfdabcdf2807ffd9bb25.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.1.1--canary.135.ea4d71e2036f9323fb24bfdabcdf2807ffd9bb25.0
yarn add @sberdevices/assistant-client@3.1.1--canary.135.ea4d71e2036f9323fb24bfdabcdf2807ffd9bb25.0
```
</details>
> fix: export ActionCommandEvent type

- cypress/integration/createAssistantDev.spec.ts
- src/assistant/assistant.ts
<details>
<summary>📦 Published PR as canary version: <code>3.1.3--canary.138.aad571b58e8495f76799803193098be65d462e43.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.1.3--canary.138.aad571b58e8495f76799803193098be65d462e43.0
yarn add @sberdevices/assistant-client@3.1.3--canary.138.aad571b58e8495f76799803193098be65d462e43.0
```
</details>
> Отправка флага первой сессии

- src/assistant/client/protocol.ts
<details>
<summary>📦 Published PR as canary version: <code>3.1.3--canary.139.070743011deb5c9600ad3f868be4fd194bb2db87.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.1.3--canary.139.070743011deb5c9600ad3f868be4fd194bb2db87.0
yarn add @sberdevices/assistant-client@3.1.3--canary.139.070743011deb5c9600ad3f868be4fd194bb2db87.0
```
</details>
> Вызов changeConfiguration крашит сокет

- src/assistant/assistant.ts
- src/assistant/client/client.ts
- src/assistant/client/protocol.ts
- src/assistant/client/transport.ts
- src/assistant/voice/voice.ts
- src/dev.ts
<details>
<summary>📦 Published PR as canary version: <code>3.2.0--canary.142.0b6a469909055cf4ebb25e80a11f93b5d335bea7.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.2.0--canary.142.0b6a469909055cf4ebb25e80a11f93b5d335bea7.0
yarn add @sberdevices/assistant-client@3.2.0--canary.142.0b6a469909055cf4ebb25e80a11f93b5d335bea7.0
```
</details>
> Рефакторинг приветствия и изменения настроек голоса

- src/assistant/assistant.ts
- src/assistant/client/client.ts
- src/assistant/client/methods.ts
- src/assistant/client/protocol.ts
<details>
<summary>📦 Published PR as canary version: <code>3.2.1--canary.141.a4a52f70508462777c549db3db4c32a674a44900.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.2.1--canary.141.a4a52f70508462777c549db3db4c32a674a44900.0
yarn add @sberdevices/assistant-client@3.2.1--canary.141.a4a52f70508462777c549db3db4c32a674a44900.0
```
</details>
> fix: Не проигрывать озвучку в ответ на текстовые сообщения

- src/assistant/voice/createNavigatorAudioProvider.ts
<details>
<summary>📦 Published PR as canary version: <code>3.2.2--canary.143.da5ebe43d4912beae154c00674da7c009f9a3345.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.2.2--canary.143.da5ebe43d4912beae154c00674da7c009f9a3345.0
yarn add @sberdevices/assistant-client@3.2.2--canary.143.da5ebe43d4912beae154c00674da7c009f9a3345.0
```
</details>
> Не работает лавашар на ios safari

- src/assistant/assistant.ts
- src/assistant/client/protocol.ts
- src/dev.ts
- src/index.ts
<details>
<summary>📦 Published PR as canary version: <code>3.3.0--canary.146.9c210de4c5edcf9736b993fc04fd7887cdb95ed4.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.3.0--canary.146.9c210de4c5edcf9736b993fc04fd7887cdb95ed4.0
yarn add @sberdevices/assistant-client@3.3.0--canary.146.9c210de4c5edcf9736b993fc04fd7887cdb95ed4.0
```
</details>
> Добавить возможность расширять meta

- src/assistant/assistant.ts
- src/assistant/client/client.ts
<details>
<summary>📦 Published PR as canary version: <code>3.3.1--canary.145.6472bd7d5981057b6015745f12a9cf942f58499a.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.3.1--canary.145.6472bd7d5981057b6015745f12a9cf942f58499a.0
yarn add @sberdevices/assistant-client@3.3.1--canary.145.6472bd7d5981057b6015745f12a9cf942f58499a.0
```
</details>
> После закрытия аппа, логика взаимодействия с аппом продолжается

- src/assistant/voice/player/voicePlayer.ts
…екорректно
<details>
<summary>📦 Published PR as canary version: <code>3.3.2--canary.151.6c14f250785aef545f784211755ba6390f01e2af.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.3.2--canary.151.6c14f250785aef545f784211755ba6390f01e2af.0
yarn add @sberdevices/assistant-client@3.3.2--canary.151.6c14f250785aef545f784211755ba6390f01e2af.0
```
</details>
> Остановка воспроизведения озвучки и последующий старт работают некорректно

- src/assistant/assistant.ts
<details>
<summary>📦 Published PR as canary version: <code>3.3.2--canary.147.cd171daca04dfa6a21329e031950dc28326ef780.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.3.2--canary.147.cd171daca04dfa6a21329e031950dc28326ef780.0
yarn add @sberdevices/assistant-client@3.3.2--canary.147.cd171daca04dfa6a21329e031950dc28326ef780.0
```
</details>
>  Ограничить время ожидания стейта от аппа

- src/index.ts
Resolves #153 
<details>
<summary>📦 Published PR as canary version: <code>3.4.1--canary.154.33321e71609b360e4bcce573f444b249367082a6.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.4.1--canary.154.33321e71609b360e4bcce573f444b249367082a6.0
yarn add @sberdevices/assistant-client@3.4.1--canary.154.33321e71609b360e4bcce573f444b249367082a6.0
```
</details>
> Параметр features отсутсвует у createAssistantDev

- src/assistant/voice/voice.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>3.4.2--canary.155.a15369ff82e8a7d3aa646dc730e09909bf38ddc3.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.4.2--canary.155.a15369ff82e8a7d3aa646dc730e09909bf38ddc3.0
yarn add @sberdevices/assistant-client@3.4.2--canary.155.a15369ff82e8a7d3aa646dc730e09909bf38ddc3.0
```
</details>
> Не останавливается озвучка, если слушание выключено

- src/assistant/client/client.ts
- src/assistant/voice/createMusicRecognizer.ts
- src/assistant/voice/createSpeechRecognizer.ts
- src/assistant/voice/createVoiceListener.ts
- src/assistant/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>3.4.3--canary.156.ef01cd284c20fc93dd9993d63015133db1007c57.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.4.3--canary.156.ef01cd284c20fc93dd9993d63015133db1007c57.0
yarn add @sberdevices/assistant-client@3.4.3--canary.156.ef01cd284c20fc93dd9993d63015133db1007c57.0
```
</details>
> Неразрезолвленный доступ к микрофону

- src/assistant/client/client.ts
- src/assistant/voice/createMusicRecognizer.ts
- src/assistant/voice/createSpeechRecognizer.ts
- src/assistant/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>3.5.0--canary.158.df51ac9198a96599eecfe7cc10985034eeaceb2f.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.5.0--canary.158.df51ac9198a96599eecfe7cc10985034eeaceb2f.0
yarn add @sberdevices/assistant-client@3.5.0--canary.158.df51ac9198a96599eecfe7cc10985034eeaceb2f.0
```
</details>
> feat: отправка cancel при отмене слушания

- src/NativePanel/NativePanel.tsx
<details>
<summary>📦 Published PR as canary version: <code>3.0.1--canary.132.a7f81cc1cb8b8e953734b661934d13f807c37ddc.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.0.1--canary.132.a7f81cc1cb8b8e953734b661934d13f807c37ddc.0
yarn add @sberdevices/assistant-client@3.0.1--canary.132.a7f81cc1cb8b8e953734b661934d13f807c37ddc.0
```
</details>
> Верстка панели в px по макету

- cypress/integration/createAssistantDev.spec.ts
- cypress/integration/greetings.spec.ts
- cypress/integration/initializeAssistantSDK.spec.ts
- cypress/integration/refreshToken.spec.ts
- cypress/support/helpers/socket.helpers.ts
- src/assistant/client/protocol.ts
<details>
<summary>📦 Published PR as canary version: <code>3.7.2--canary.159.3a997572dd009b435aec9f63b7fa85330761d6e4.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.7.2--canary.159.3a997572dd009b435aec9f63b7fa85330761d6e4.0
yarn add @sberdevices/assistant-client@3.7.2--canary.159.3a997572dd009b435aec9f63b7fa85330761d6e4.0
```
</details>
> Обновление токена должно вызывать подключение

- src/assistant/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>3.7.3--canary.160.03a1d2d4deedd9a6c67886f55a7dbb408995aea7.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.7.3--canary.160.03a1d2d4deedd9a6c67886f55a7dbb408995aea7.0
yarn add @sberdevices/assistant-client@3.7.3--canary.160.03a1d2d4deedd9a6c67886f55a7dbb408995aea7.0
```
</details>
> fix: возможность останавливать слушание

- src/assistant/client/protocol.ts
<details>
<summary>📦 Published PR as canary version: <code>3.8.0--canary.164.2567be318fe6cc6022674c270fff8aeffb8c3503.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.8.0--canary.164.2567be318fe6cc6022674c270fff8aeffb8c3503.0
yarn add @sberdevices/assistant-client@3.8.0--canary.164.2567be318fe6cc6022674c270fff8aeffb8c3503.0
```
</details>
> Отправлять additionalInfo

- src/assistant/assistant.ts
- src/assistant/voice/player/voicePlayer.ts
- src/assistant/voice/voice.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>3.8.1--canary.166.52fc3152eec35b364b5cc01a3ebf7ea1ab76f05a.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.8.1--canary.166.52fc3152eec35b364b5cc01a3ebf7ea1ab76f05a.0
yarn add @sberdevices/assistant-client@3.8.1--canary.166.52fc3152eec35b364b5cc01a3ebf7ea1ab76f05a.0
```
</details>
> Не воспроизводить озвучку, если плеер не готов

- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>3.9.0--canary.170.3944ff197944f47df447daecfc345f4067c228f7.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@3.9.0--canary.170.3944ff197944f47df447daecfc345f4067c228f7.0
yarn add @sberdevices/assistant-client@3.9.0--canary.170.3944ff197944f47df447daecfc345f4067c228f7.0
```
</details>
> Поддержать команду visiblity

- cypress/integration/greetings.spec.ts
- cypress/integration/refreshToken.spec.ts
- src/assistant/assistant.ts
- src/assistant/client/client.ts
- src/assistant/client/protocol.ts
- src/dev.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>4.0.0--canary.168.99d7671e8dfaa4602d1708c2a320a3b40cbf90d2.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.0.0--canary.168.99d7671e8dfaa4602d1708c2a320a3b40cbf90d2.0
yarn add @sberdevices/assistant-client@4.0.0--canary.168.99d7671e8dfaa4602d1708c2a320a3b40cbf90d2.0
```
</details>
> Запрашивать токен перед коннектом

- cypress/integration/disableDubbing.spec.ts
- src/assistant/assistant.ts
- src/assistant/client/protocol.ts
<details>
<summary>📦 Published PR as canary version: <code>4.0.1--canary.172.839903d45b274252648f0479a4c494e3a3e5d83f.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.0.1--canary.172.839903d45b274252648f0479a4c494e3a3e5d83f.0
yarn add @sberdevices/assistant-client@4.0.1--canary.172.839903d45b274252648f0479a4c494e3a3e5d83f.0
```
</details>
> changeSettings не должен создавать коннект

- cypress/integration/createAssistant.spec.ts
- src/createAssistant.ts
- src/debug.ts
- src/dev.ts
- src/mock.ts
- src/typings.ts
Closes #179 
<details>
<summary>📦 Published PR as canary version: <code>4.1.0--canary.180.e787923bd251044ab78df0620567ac40ab779a44.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.1.0--canary.180.e787923bd251044ab78df0620567ac40ab779a44.0
yarn add @sberdevices/assistant-client@4.1.0--canary.180.e787923bd251044ab78df0620567ac40ab779a44.0
```
</details>
> feat: Добавить методы setSuggests и setHints

- cypress/integration/createAssistantDev.spec.ts
- src/assistant/client/client.ts
<details>
<summary>📦 Published PR as canary version: <code>4.3.1--canary.184.17094815990a302a26563229398dbee0a7530701.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.3.1--canary.184.17094815990a302a26563229398dbee0a7530701.0
yarn add @sberdevices/assistant-client@4.3.1--canary.184.17094815990a302a26563229398dbee0a7530701.0
```
</details>
> Не работают подписки sendAction в браузере

- .gitignore
- examples/todo-canvas-app/package-lock.json
- examples/todo-canvas-app/package.json
- examples/todo-canvas-app/tsconfig.json
<details>
<summary>📦 Published PR as canary version: <code>4.3.2--canary.188.e6d89c365c618abdd8cdbadc17ca798d30220e09.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.3.2--canary.188.e6d89c365c618abdd8cdbadc17ca798d30220e09.0
yarn add @sberdevices/assistant-client@4.3.2--canary.188.e6d89c365c618abdd8cdbadc17ca798d30220e09.0
```
</details>
> Починил запуск todo-canvas-app

- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>4.4.0--canary.195.3a667264893389b853b70286632c53c4eac5b11b.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.4.0--canary.195.3a667264893389b853b70286632c53c4eac5b11b.0
yarn add @sberdevices/assistant-client@4.4.0--canary.195.3a667264893389b853b70286632c53c4eac5b11b.0
```
</details>
> Добавлен тип AssistantThemeCommand

- src/createAssistant.ts
- src/createAssistantDev.ts
<details>
<summary>📦 Published PR as canary version: <code>4.4.0--canary.186.2ab5d7d316a5140309b676be55e935ca8b306853.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.4.0--canary.186.2ab5d7d316a5140309b676be55e935ca8b306853.0
yarn add @sberdevices/assistant-client@4.4.0--canary.186.2ab5d7d316a5140309b676be55e935ca8b306853.0
```
</details>
> Приложение может управлять ready

- src/assistant/client/protocol.ts
<details>
<summary>📦 Published PR as canary version: <code>4.5.1--canary.185.8981adcb9163fa2d9b15c817bd1447538db313ed.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.5.1--canary.185.8981adcb9163fa2d9b15c817bd1447538db313ed.0
yarn add @sberdevices/assistant-client@4.5.1--canary.185.8981adcb9163fa2d9b15c817bd1447538db313ed.0
```
</details>
> fix: merge additionaInfo in updateDevice

- README.md
- package.json
- rollup.config.js
Resolves #162 
<details>
<summary>📦 Published PR as canary version: <code>4.6.1--canary.203.6d9b8b9274c65863d60fa88f14ef9aa84fc45052.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.6.1--canary.203.6d9b8b9274c65863d60fa88f14ef9aa84fc45052.0
yarn add @sberdevices/assistant-client@4.6.1--canary.203.6d9b8b9274c65863d60fa88f14ef9aa84fc45052.0
```
</details>
> Собирать 2 umd билда

- README.md
<details>
<summary>📦 Published PR as canary version: <code>4.6.1--canary.204.41bd367f728e700d45b989943a044800197ed2b8.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.6.1--canary.204.41bd367f728e700d45b989943a044800197ed2b8.0
yarn add @sberdevices/assistant-client@4.6.1--canary.204.41bd367f728e700d45b989943a044800197ed2b8.0
```
</details>
> docs: Откатил изменения предыдущего коммита

- cypress/integration/createAssistant.spec.ts
- src/createAssistant.ts
- src/typings.ts
close #202 
<details>
<summary>📦 Published PR as canary version: <code>4.10.0--canary.228.4b6c5c9baa715de142aea8ffb0d1e7cb3b358ae6.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.10.0--canary.228.4b6c5c9baa715de142aea8ffb0d1e7cb3b358ae6.0
yarn add @sberdevices/assistant-client@4.10.0--canary.228.4b6c5c9baa715de142aea8ffb0d1e7cb3b358ae6.0
```
</details>
> Удобные методы для установки suggests и hints

- package-lock.json
- package.json
- rollup.config.js
closes #229 
<details>
<summary>📦 Published PR as canary version: <code>4.10.1--canary.230.a5ab34c4c394213c695b690897e09d6338bb2108.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.10.1--canary.230.a5ab34c4c394213c695b690897e09d6338bb2108.0
yarn add @sberdevices/assistant-client@4.10.1--canary.230.a5ab34c4c394213c695b690897e09d6338bb2108.0
```
</details>
> chore: Ошибка при сборке

- package-lock.json
- package.json
- src/assistantSdk/assistant.ts
- src/typings.ts
- tsconfig.json
<details>
<summary>📦 Published PR as canary version: <code>4.11.0--canary.231.f76657ef84ea8af1cc9cc2aa02f1463a9ffc538a.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.11.0--canary.231.f76657ef84ea8af1cc9cc2aa02f1463a9ffc538a.0
yarn add @sberdevices/assistant-client@4.11.0--canary.231.f76657ef84ea8af1cc9cc2aa02f1463a9ffc538a.0
```
</details>
> feat: Добавлена поддержка BackgroundApps

- src/assistantSdk/voice/listener/navigatorAudioProvider.ts
<details>
<summary>📦 Published PR as canary version: <code>4.10.2--canary.238.308aeed034f9f168a331cf78408e2838e1667ce5.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.10.2--canary.238.308aeed034f9f168a331cf78408e2838e1667ce5.0
yarn add @sberdevices/assistant-client@4.10.2--canary.238.308aeed034f9f168a331cf78408e2838e1667ce5.0
```
</details>
> fix: Исправлен момент отправки эмоции listen при готовности захвата речи

- README.md
<details>
<summary>📦 Published PR as canary version: <code>4.11.2--canary.239.a04e95f7b1864ffb4b1fda313042e452939e2aed.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.11.2--canary.239.a04e95f7b1864ffb4b1fda313042e452939e2aed.0
yarn add @sberdevices/assistant-client@4.11.2--canary.239.a04e95f7b1864ffb4b1fda313042e452939e2aed.0
```
</details>
> docs: Ссылки в альтернативном подключении

- src/assistantSdk/assistant.ts
<details>
<summary>📦 Published PR as canary version: <code>4.11.2--canary.246.98d032e125bd92a3413082d25a0b6e7639ea386c.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.11.2--canary.246.98d032e125bd92a3413082d25a0b6e7639ea386c.0
yarn add @sberdevices/assistant-client@4.11.2--canary.246.98d032e125bd92a3413082d25a0b6e7639ea386c.0
```
</details>
> fix: Удалён метод Promise.allSettled

- src/assistantSdk/assistant.ts
<details>
<summary>📦 Published PR as canary version: <code>4.12.1--canary.242.f3da956d84efd7c9a9121f3c8fc2a3be44cd4943.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.12.1--canary.242.f3da956d84efd7c9a9121f3c8fc2a3be44cd4943.0
yarn add @sberdevices/assistant-client@4.12.1--canary.242.f3da956d84efd7c9a9121f3c8fc2a3be44cd4943.0
```
</details>
> fix: Исправлен асинхронный сбор меты background_apps

- src/assistantSdk/assistant.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>4.14.0--canary.248.7868ebf44498210539f2c9dbd8e3d01bfd821aa2.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.14.0--canary.248.7868ebf44498210539f2c9dbd8e3d01bfd821aa2.0
yarn add @sberdevices/assistant-client@4.14.0--canary.248.7868ebf44498210539f2c9dbd8e3d01bfd821aa2.0
```
</details>
> feat: Добавлен эмитер StartSmartSearch

- README.md
<details>
<summary>📦 Published PR as canary version: <code>4.14.1--canary.249.400c5f2809b2cf3d93dd11f76be47425146ca6c9.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.14.1--canary.249.400c5f2809b2cf3d93dd11f76be47425146ca6c9.0
yarn add @sberdevices/assistant-client@4.14.1--canary.249.400c5f2809b2cf3d93dd11f76be47425146ca6c9.0
```
</details>
> docs: Добавлено описание AssistantThemeCommand

- src/createAssistant.ts
Реализация метода `findInInitialData` для #247
<details>
<summary>📦 Published PR as canary version: <code>4.15.0--canary.252.dd7ce278844629b3f2938009bf5445e2af3ba565.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.15.0--canary.252.dd7ce278844629b3f2938009bf5445e2af3ba565.0
yarn add @sberdevices/assistant-client@4.15.0--canary.252.dd7ce278844629b3f2938009bf5445e2af3ba565.0
```
</details>
> feat: метод findInInitialData

- README.md
- src/createAssistantDev.ts
Closes #245 
<details>
<summary>📦 Published PR as canary version: <code>4.17.0--canary.254.a9ab08a9c7236f0aa8e7f38e5ad4f78d3714afd4.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.17.0--canary.254.a9ab08a9c7236f0aa8e7f38e5ad4f78d3714afd4.0
yarn add @sberdevices/assistant-client@4.17.0--canary.254.a9ab08a9c7236f0aa8e7f38e5ad4f78d3714afd4.0
```
</details>
> Добавить параметр для выбора поверхности

- src/createAssistant.ts
<details>
<summary>📦 Published PR as canary version: <code>4.17.2--canary.262.d6f9696e85d65b851d7329c59b84e402b0c223fd.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.17.2--canary.262.d6f9696e85d65b851d7329c59b84e402b0c223fd.0
yarn add @sberdevices/assistant-client@4.17.2--canary.262.d6f9696e85d65b851d7329c59b84e402b0c223fd.0
```
</details>
> Не падать в ноде

- cypress/support/helpers/socket.helpers.ts
- src/assistantSdk/assistant.ts
Closes #261 
<details>
<summary>📦 Published PR as canary version: <code>4.17.2--canary.265.b706e33b583084fd7abeb434dd8d1c5595c2224a.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.17.2--canary.265.b706e33b583084fd7abeb434dd8d1c5595c2224a.0
yarn add @sberdevices/assistant-client@4.17.2--canary.265.b706e33b583084fd7abeb434dd8d1c5595c2224a.0
```
</details>
> Стейт не приходит в сценарий

- src/createAssistant.ts
<details>
<summary>📦 Published PR as canary version: <code>4.17.2--canary.263.c5e13fa2a6240c51c1c764a54b120b4b6f3a16d7.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.17.2--canary.263.c5e13fa2a6240c51c1c764a54b120b4b6f3a16d7.0
yarn add @sberdevices/assistant-client@4.17.2--canary.263.c5e13fa2a6240c51c1c764a54b120b4b6f3a16d7.0
```
</details>
> fix: После отписки, команды не приходят в on('data')

- src/assistantSdk/voice/voice.ts
- src/index.ts
<details>
<summary>📦 Published PR as canary version: <code>4.19.0--canary.260.d4cacc7f74843d704f70a1e08b370810be8fed17.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.19.0--canary.260.d4cacc7f74843d704f70a1e08b370810be8fed17.0
yarn add @sberdevices/assistant-client@4.19.0--canary.260.d4cacc7f74843d704f70a1e08b370810be8fed17.0
```
</details>
> feat: Добавлена возможность подклеивать ArrayBuffer[] к голосовому сообщению

- src/assistantSdk/voice/voice.ts
<details>
<summary>📦 Published PR as canary version: <code>4.19.1--canary.273.cbb41d41920b77f2570a8e4091de900bc17fa2d5.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.19.1--canary.273.cbb41d41920b77f2570a8e4091de900bc17fa2d5.0
yarn add @sberdevices/assistant-client@4.19.1--canary.273.cbb41d41920b77f2570a8e4091de900bc17fa2d5.0
```
</details>
> После включения озвучки не срабатывает автослушивание

- cypress/integration/createAssistantWeb.spec.ts
- src/assistantSdk/assistant.ts
- src/createAssistant.ts
- src/dev.ts
- src/typings.ts
<details>
<summary>📦 Published PR as canary version: <code>4.20.0--canary.276.0b86ed74d732ebec78a690d6b83de6791a456581.0</code></summary>
<br />
```bash
npm install @sberdevices/assistant-client@4.20.0--canary.276.0b86ed74d732ebec78a690d6b83de6791a456581.0
yarn add @sberdevices/assistant-client@4.20.0--canary.276.0b86ed74d732ebec78a690d6b83de6791a456581.0
```
</details>
> Поддержка system back
